# mise registry
# https://mise.jdx.dev/registry.html#tools
[tools]
biome = "latest"
deno = "latest"
direnv = "latest"
go = "latest"
hadolint = "latest"
helm = "latest"
jq = "latest"
kubectl = "latest"
pnpm = "latest"
usage = "latest"
uv = "latest"
yq = "latest"

# Tasks
# https://mise.jdx.dev/tasks/
[tasks.setup-uv-tools]
description = "uv tools の一括インストール"
run = """
uv tool install awsume
uv tool install json-schema-for-humans
uv tool install parquet-tools
uv tool install pproxy
uv tool install pre-commit
uv tool install sqlfluff
"""
